services:
  - type: web
    name: taq-portfolio-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://taq-folio.vercel.app # Removed trailing slash 